FROM python:3.8
WORKDIR /code
COPY ./ms_7_stats/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir
WORKDIR /code/logs
COPY ./logs/app.log ./
WORKDIR /code/common
COPY ./common/*.py ./
WORKDIR /code/ms_7_stats
COPY ./ms_7_stats/*.py ./
CMD ["python3", "ms_7_stats.py"]
