FROM python:3.8
WORKDIR /code
COPY ./ms_2_db/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir
WORKDIR /code/logs
COPY ./logs/app.log ./
WORKDIR /code/common
COPY ./common/*.py ./
WORKDIR /code/ms_2_db
COPY ./ms_2_db/*.py ./
CMD ["python3", "ms_2_db.py"]
