FROM python:3.8
WORKDIR /code
COPY ./ms_5_fp/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir
WORKDIR /code/logs
COPY ./logs/app.log ./
WORKDIR /code/common
COPY ./common/*.py ./
WORKDIR /code/ms_5_fp
COPY ./ms_5_fp/*.py ./
CMD ["python3", "ms_5_fp.py"]
