FROM python:3.8
WORKDIR /code
COPY ./ms_4_urlp/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir
WORKDIR /code/logs
COPY ./logs/app.log ./
WORKDIR /code/common
COPY ./common/*.py ./
WORKDIR /code/ms_4_urlp
COPY ./ms_4_urlp/*.py ./
CMD ["python3", "ms_4_urlp.py"]
