FROM python:3.8
WORKDIR /code
COPY ./ms_1_ui/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir
WORKDIR /code/logs
COPY ./logs/app.log ./
WORKDIR /code/common
COPY ./common/*.py ./
WORKDIR /code/ms_1_ui
COPY ./ms_1_ui/*.py ./
CMD ["python3", "ms_1_ui.py"]
