name: CD

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push \ ui
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_1_ui/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_1_ui

      - name: Build and push \ db
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_2_db/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_2_db

      - name: Build and push \ mb
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_3_mb/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_3_mb

      - name: Build and push \ urlp
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_4_urlp/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_4_urlp

      - name: Build and push \ fp
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_5_fp/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_5_fp

      - name: Build and push \ cache
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_6_cache/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_6_cache

      - name: Build and push \ stats
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_7_stats/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_7_stats