name: CD_ms_3_mb

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push \ mb
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ms_3_mb/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python_bootcamp_hw_22_2:ms_3_mb